name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        working-directory: ./app

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
        working-directory: ./app

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        working-directory: ./app
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
  
